number_list =[1,7,9,20]
number_list .append(30)
number_list .insert(5,11)
number_list .remove (9)
number_list  .sort()
number_list .reverse()
print(number_list )
print (12 in number_list )
print(number_list.count(1))
print(number_list.index(7))
number_list .pop ()
number_list_2= number_list .copy()
number_list_2.clear()
print(number_list_2)